keys:
  - &dominion age1wukgfrjpl3l3wdw5m2y703v2fkjangpzxs9ct4wev4ylwv7sycvszp6cgp
  - &system age1s2rdn4ws8qnme8kaau6m4s8dfx8anq6rsgvv7vmhr7j4h292n3cshl52em
creation_rules:
  - path_regex: .*secrets.yml
    key_groups:
      - age:
          - *dominion
          - *system
